// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatId               string   `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ConversationId       string   `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserInput            string   `protobuf:"bytes,4,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MessageRequest) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *MessageRequest) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *MessageRequest) GetUserInput() string {
	if m != nil {
		return m.UserInput
	}
	return ""
}

type MessageResponse struct {
	ServerResponse       string   `protobuf:"bytes,1,opt,name=server_response,json=serverResponse,proto3" json:"server_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetServerResponse() string {
	if m != nil {
		return m.ServerResponse
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageRequest)(nil), "chat.MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "chat.MessageResponse")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xba, 0x18, 0xb9, 0xf8, 0x7c,
	0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xc4, 0xb9,
	0xd8, 0x4b, 0x8b, 0x53, 0x8b, 0xe2, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xd8,
	0x40, 0x5c, 0xcf, 0x14, 0x90, 0x04, 0x48, 0x0f, 0x48, 0x82, 0x09, 0x22, 0x01, 0xe2, 0x7a, 0xa6,
	0x08, 0xa9, 0x73, 0xf1, 0x27, 0xe7, 0xe7, 0x95, 0xa5, 0x16, 0x15, 0x27, 0x96, 0x64, 0xe6, 0xe7,
	0x81, 0x14, 0x30, 0x83, 0x15, 0xf0, 0x21, 0x0b, 0x7b, 0xa6, 0x08, 0xc9, 0x72, 0x71, 0x41, 0x8c,
	0xce, 0x2b, 0x28, 0x2d, 0x91, 0x60, 0x01, 0xab, 0xe1, 0x04, 0x9b, 0x0e, 0x12, 0x50, 0xb2, 0xe2,
	0xe2, 0x87, 0xbb, 0xa5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0x64, 0x74, 0x71, 0x6a, 0x51, 0x59,
	0x6a, 0x51, 0x7c, 0x11, 0x54, 0x08, 0xea, 0x28, 0x3e, 0x88, 0x30, 0x4c, 0xa1, 0x91, 0x23, 0x17,
	0x8b, 0x73, 0x46, 0x62, 0x89, 0x90, 0x25, 0x17, 0x97, 0x7b, 0x6a, 0x09, 0xd4, 0x18, 0x21, 0x11,
	0x3d, 0xb0, 0x8f, 0x51, 0x7d, 0x28, 0x25, 0x8a, 0x26, 0x0a, 0x31, 0x22, 0x89, 0x0d, 0x1c, 0x30,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0xf6, 0xff, 0x9b, 0x26, 0x01, 0x00, 0x00,
}
